###
# Minimal Configuration File
#
# This configuration strips services to the absolute bare essentials to function.
# Very useful for reverse proxy configurations where a user would override networking anyways.
###
services:
  ##
  # -- Panel Cron --
  # These are required for schedules and other misc tasks to 
  # function correctly.
  ##
  cron:
    command: p:cron
    extends:
      service: panel
    ports: !reset
  ##
  # -- Pelican Daemon --
  # This service provides the wings runtime.
  ##
  daemon:
    environment:
      - TZ=${DAEMON_TIMEZONE:-UTC}
    image: docker.io/thecrafter22/pelican-daemon:${DAEMON_VERSION:-latest}
    privileged: true
    profiles: [ daemon ]
    restart: always
    volumes:
      - ${DAEMON_DATA_DIRECTORY:-/var/lib/pelican}:${DAEMON_DATA_DIRECTORY:-/var/lib/pelican}
      - ${DOCKER_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock
      - /tmp/pelican/:/tmp/pelican/:z
      - ./conf.d/daemon:/etc/pelican:z
      - ./conf.d/letsencrypt:/etc/letsencrypt:ro,z
      - ./conf.d/certs:/etc/certs:ro,z
    working_dir: ${DAEMON_DATA_DIRECTORY:-/var/lib/pelican}
  ##
  # -- Pelican Panel --
  # This is the container that provides the main web interface.
  ##
  panel:
    env_file: ./conf.d/panel.env
    image: docker.io/thecrafter22/pelican-panel:${PANEL_VERSION:-latest}
    profiles: [ panel ]
    restart: always
    volumes:
      - ./data/panel:/data:z
  ##
  # -- Panel Worker --
  ##
    worker:
    command: p:worker
    extends:
      service: panel
    ports: !reset
