###
# Build Configuration File
#
# This is considered the base configuration for this repo.
# Everything to build and deploy pelican is in here.
###
services:
  ##
  # -- Let's Encrypt Certbot --
  ##
  certbot:
    command: renew
    image: docker.io/certbot/certbot:latest
    profiles: [ letsencrypt ]
    volumes:
      - ./conf.d/letsencrypt:/etc/letsencrypt
      - ./conf.d/letsencrypt/webroot/.well-known:/var/www/html/public/.well-known
  ##
  # -- Panel Cron --
  # These are required for schedules and other misc tasks to 
  # function correctly.
  ##
  cron:
    command: p:cron
    env_file: ./conf.d/panel.env
    image: thecrafter22/pelican-panel:${PANEL_VERSION:-latest}
    profiles: [ panel ]
    restart: always
    volumes:
      - ./data/panel:/data
  ##
  # -- Pelican Daemon --
  # This service provides the wings runtime.
  ##
  daemon:
    build:
      args:
        VERSION: ${DAEMON_VERSION}
      context: ./manifest/images/daemon
    environment:
      - TZ=${DAEMON_TIMEZONE:-UTC}
    image: docker.io/thecrafter22/pelican-daemon:${DAEMON_VERSION:-latest}
    ports:
      - 2022:2022
      - 8080:8080
    privileged: true
    profiles: [ daemon ]
    restart: always
    volumes:
      - ${DAEMON_DATA_DIRECTORY:-/var/lib/pelican}:${DAEMON_DATA_DIRECTORY:-/var/lib/pelican}
      - ${DOCKER_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock
      - /tmp/pelican/:/tmp/pelican/
      - ./conf.d/daemon:/etc/pelican
      - ./conf.d/letsencrypt:/etc/letsencrypt:ro
      - ./conf.d/certs:/etc/certs:ro
    working_dir: ${DAEMON_DATA_DIRECTORY:-/var/lib/pelican}
  ##
  # -- Pelican Panel --
  # This is the container that provides the main web interface.
  ##
  panel:
    build:
      args:
        VERSION: ${PANEL_VERSION}
      context: ./manifest/images/panel
    env_file: ./conf.d/panel.env
    image: docker.io/thecrafter22/pelican-panel:${PANEL_VERSION:-latest}
    ports:
      - 80:80
      - 443:443
    profiles: [ panel ]
    restart: always
    volumes:
      - ./data/panel:/data
      - ./conf.d/letsencrypt:/etc/letsencrypt
      - ./conf.d/letsencrypt/webroot/.well-known:/var/www/html/public/.well-known
      - ./conf.d/certs:/etc/certs
  ##
  # -- Panel Worker --
  ##
  worker:
    command: p:worker
    env_file: ./conf.d/panel.env
    image: docker.io/thecrafter22/pelican-panel:${PANEL_VERSION:-latest}
    profiles: [ panel ]
    restart: always
    volumes:
      - ./data/panel:/data
